default_platform(:android)

platform :android do
  desc "Build the Android App"
  lane :android_release do
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
  end

  desc "Submit a new version to the internal track in the Google Play"
  lane :deploy_internal do
    gradle(task: "clean")
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )

    json_path = "jsonFile.json"
    File.write(json_path,ENV['GOOGLE_PLAY_SERVICE_ACCOUNT_JSON'])

    # Upload to the internal track
    upload_to_play_store(
      track: 'internal',
      json_key: json_path
    )

    # Optional: Clean up the service account JSON after use
    sh "rm service-account.json"
  end
end
