platform :android do
  desc "Build the Android App"
  lane :android_release do
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
  end

  desc "Submit a new version to the internal track in the Google Play"
  lane :deploy_internal do
    gradle(task: "clean")
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )

    # Path to the service account JSON
    json_path = "/tmp/service-account.json"

    # Upload to the internal track
    upload_to_play_store(
      track: 'internal',
      json_key: json_path
    )

    # Clean up the service account JSON after use
    sh "rm #{json_path}"
  end
end
